# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    providers:
        chain_provider:
            chain:
              providers: [users_db]
        users_db:
            entity:
                class: 'Jaltamir\BoxCoreBundle\Entity\User'
                property: 'email'

    encoders:
        Jaltamir\BoxCoreBundle\Entity\User:
            algorithm: 'sha512'
            encode_as_base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                always_use_default_target_path: true
                default_target_path: home
                login_path: login
                check_path: login
            logout:
                path: logout
                target: home
                invalidate_session: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/perfil, roles: ROLE_USER }
        - { path: ^/reservas, roles: ROLE_USER }
        - { path: ^/seleccionar-abono, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }